---
title: "Dashboard Maraton"
output: 
  flexdashboard::flex_dashboard:
    theme:
      bg: "#101010"
      fg: "#FDF7F7" 
      primary: "#ED79F9"
      base_font:
        google: Prompt
      code_font:
        google: JetBrains Mono
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(dbplyr)
library(lubridate)
library(tm)
library(ggplot2)
library(wordcloud)
# Install thematic and un-comment for themed static plots (i.e., ggplot2)
# thematic::thematic_rmd()
```
```{r}
library(paqueteMET)
data("CarreraLuz22")
```

Column {data-width=650 .tabset}
-----------------------------------------------------------------------

### Promedio Edad

```{r}
valueBox(round(mean(CarreraLuz22$edad)))
```

### Edades

```{r}
barplot(table(CarreraLuz22$edad))
```

### Edades

```{r}
barplot(table(CarreraLuz22$edad))
```

Column {data-width=350}
-----------------------------------------------------------------------

### Participación por Genero 

```{r}
pie(table(CarreraLuz22$sex))
```

###  Mejor Tiempo 

```{r}
valueBox(round(max((CarreraLuz22$timerun/60)),2),"min")

```

